# Generated by Django 6.0.1 on 2026-01-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='created_for_user',
            new_name='user',
        ),
        migrations.AddField(
            model_name='module',
            name='resource_url',
            field=models.URLField(default='https://google.com', help_text='Link to the video/article'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='warmup_text',
            field=models.TextField(default='Legacy content', help_text='Gemini generated glue content'),
            preserve_default=False,
        ),
    ]
