# Generated by Django 6.0.1 on 2026-01-24 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_created_for_user_course_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_project_based',
            field=models.BooleanField(default=False, help_text='Does this require code submission?'),
        ),
        migrations.AddField(
            model_name='module',
            name='remedial_text',
            field=models.TextField(blank=True, help_text='Extra lesson if they got a Soft Pass (60-74%)', null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='resource_url',
            field=models.URLField(default='https://google.com'),
        ),
        migrations.AlterField(
            model_name='module',
            name='warmup_text',
            field=models.TextField(default='Legacy content'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500)),
                ('option_a', models.CharField(max_length=200)),
                ('option_b', models.CharField(max_length=200)),
                ('option_c', models.CharField(max_length=200)),
                ('correct_option', models.CharField(max_length=1)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.module')),
            ],
        ),
    ]
