# Generated by Django 6.0.1 on 2026-02-06 07:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_module_is_project_based_module_remedial_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='topic',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('user', 'topic'), name='one_course_per_user_per_topic'),
        ),
    ]
