# Generated by Django 6.0.1 on 2026-02-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_module_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='remedial_consumed',
            field=models.BooleanField(default=False),
        ),
    ]
