# Generated by Django 6.0.1 on 2026-02-06 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_topic_course_one_course_per_user_per_topic'),
        ('guardian', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimentlog',
            name='module',
            field=models.ForeignKey(blank=True, help_text='Module where the sentiment was detected', null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.module'),
        ),
    ]
